# Generated by Django 4.1.5 on 2023-03-01 12:00

from django.db import migrations, models
import myauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=1, upload_to=myauth.models.profile_images_directory_path),
            preserve_default=False,
        ),
    ]
