# Generated by Django 4.1.5 on 2023-06-05 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='number_rooms',
            field=models.IntegerField(default=1, verbose_name='number of rooms'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='total_area',
            field=models.IntegerField(verbose_name='total area'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='type_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_house.typeroom', verbose_name='type of room'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
