# Generated by Django 4.1.5 on 2023-02-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_blog_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='gallere',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
