# Generated by Django 4.1.5 on 2023-03-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='gallere',
            new_name='gallery',
        ),
    ]
