# Generated by Django 4.1.5 on 2023-03-05 12:02

import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_rename_gallere_blog_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to=blog_app.models.profile_images_directory_path),
        ),
    ]
