# Generated by Django 4.1.5 on 2023-03-05 12:20

import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='gallery',
            field=models.ImageField(blank=True, upload_to=blog_app.models.blog_gallery_directory_path),
        ),
    ]
