# Generated by Django 4.1.5 on 2023-03-12 09:41

import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_rename_user_id_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=blog_app.models.profile_images_directory_path),
        ),
    ]
