# Generated by Django 4.1.7 on 2023-03-17 09:42

import blog_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_alter_blog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='gallery',
        ),
        migrations.CreateModel(
            name='BlogGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ImageField(blank=True, upload_to=blog_app.models.blog_gallery_directory_path)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.blog')),
            ],
        ),
    ]
