# Generated by Django 4.1.5 on 2023-03-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_remove_blog_gallery_bloggallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggallery',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='blog_app.blog'),
        ),
    ]
